### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by jamiebyer** [jamiebyer/hydro-thiem-dupuit-forchheimer#1]
- [x]  Scale back so it looks like https://github.com/fhmjones/hydro-thiem . Ali really only wants it to "answer" one question. That is: "what will the drawdown curve look like for various outflow or transmissivity values?" If he wants this app to answer other questions, we'll incorporate them later.

- NOTE my code is probably awkward and its may be more efficient to get there with your own adjustments. Maybe even start a new "app.py".

- [ ]  Low priority: Might be nice to put the graph on a figure, but aligning the pieces of the figure with the plotted curve might get finicky.

- [x]  new task: lets continue to use md file for introductory information. Which raises the next question or task:

- [x]  new task: (lower priority) can we get a figure into the "introductory" text? This would be nice, but "smaller".

**Comment by fhmjones** [comment]
Looking great! 
- [ ] Make a markdown file for an introduction. It can be "trivial" for now - maybe a statement from the "readme", plus a pointer to the origin of figures we're borrowing. 
- [ ] The one figure is great. Let's have two figures: one that's there (for the confined aquifer situation) and another similar from the spreadsheet [here](https://docs.google.com/spreadsheets/d/14ctwoJyRe8ex4IC3RjZh2jilDXbMkqTO/edit#gid=492511278). Resize these so they can fit side by side, and add the figure's titles to the PNG files: "Steady-state flow to a well in an CONFINED aquifer" and "Steady-state flow to a well in an UNCONFINED aquifer". If two side by side is "hard", maybe just combine as a single PNG. (I can prepare the two (or one combined) figures if you like - just let me know.)
- [ ] rename the two tabs "Confined aquifer (Thiem)" and "Unconfined aquifer (Dupuit-Forchheimer)". 
- [ ] add a "Sources" section, with credit to the videos & spreadsheets for "inspiration" and the figures, plus you as programmer.
